apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ap7ne8452-go 
  janus-idp.io/tekton: ap7ne8452-go
  backstage.io/kubernetes-id: ap7ne8452-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ap7ne8452-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml