apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ap7ne8452-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ap7ne8452-go 
  name: ap7ne8452-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ap7ne8452-go 
